// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionsTech.MVC.Data;

#nullable disable

namespace SolutionsTech.MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionsTech.MVC.Models.Brand", b =>
                {
                    b.Property<long>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBrand"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBrand");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.FormPayment", b =>
                {
                    b.Property<long>("IdFormPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFormPayment"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormPayment");

                    b.ToTable("FormPayment");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.Product", b =>
                {
                    b.Property<long>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProduct"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("BrandIdBrand")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduct");

                    b.HasIndex("BrandIdBrand");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.Scheduling", b =>
                {
                    b.Property<long>("IdScheduling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdScheduling"));

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdFormPayment")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdScheduling");

                    b.HasIndex("IdFormPayment");

                    b.HasIndex("IdUser");

                    b.ToTable("Scheduling");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.SchedulingProcedure", b =>
                {
                    b.Property<long>("IdSchedulingProcedure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSchedulingProcedure"));

                    b.Property<long>("SchedulingIdScheduling")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeProcedureIdTypeProcedure")
                        .HasColumnType("bigint");

                    b.HasKey("IdSchedulingProcedure");

                    b.HasIndex("SchedulingIdScheduling");

                    b.HasIndex("TypeProcedureIdTypeProcedure");

                    b.ToTable("SchedulingProcedure");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.SchedulingProduct", b =>
                {
                    b.Property<long>("IdSchedulingProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSchedulingProduct"));

                    b.Property<long>("ProductIdProduct")
                        .HasColumnType("bigint");

                    b.Property<long>("SchedulingIdScheduling")
                        .HasColumnType("bigint");

                    b.HasKey("IdSchedulingProduct");

                    b.HasIndex("ProductIdProduct");

                    b.HasIndex("SchedulingIdScheduling");

                    b.ToTable("SchedulingProduct");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.TypeProcedure", b =>
                {
                    b.Property<long>("IdTypeProcedure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTypeProcedure"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTypeProcedure");

                    b.ToTable("TypeProcedure");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUser"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDeactivation")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdUserType")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.UserType", b =>
                {
                    b.Property<long>("IdUserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUserType"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserType");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.Product", b =>
                {
                    b.HasOne("SolutionsTech.MVC.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandIdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.Scheduling", b =>
                {
                    b.HasOne("SolutionsTech.MVC.Models.FormPayment", "FormPayment")
                        .WithMany()
                        .HasForeignKey("IdFormPayment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionsTech.MVC.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.SchedulingProcedure", b =>
                {
                    b.HasOne("SolutionsTech.MVC.Models.Scheduling", "Scheduling")
                        .WithMany()
                        .HasForeignKey("SchedulingIdScheduling")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionsTech.MVC.Models.TypeProcedure", "TypeProcedure")
                        .WithMany()
                        .HasForeignKey("TypeProcedureIdTypeProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheduling");

                    b.Navigation("TypeProcedure");
                });

            modelBuilder.Entity("SolutionsTech.MVC.Models.SchedulingProduct", b =>
                {
                    b.HasOne("SolutionsTech.MVC.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductIdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionsTech.MVC.Models.Scheduling", "Scheduling")
                        .WithMany()
                        .HasForeignKey("SchedulingIdScheduling")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Scheduling");
                });
#pragma warning restore 612, 618
        }
    }
}
